// Code generated by "stringer -type=flateType"; DO NOT EDIT

package compressedhandler

import "fmt"

const _flateType_name = "IdentityDeflateGzip"

var _flateType_index = [...]uint8{0, 8, 15, 19}

func (i flateType) String() string {
	if i >= flateType(len(_flateType_index)-1) {
		return fmt.Sprintf("flateType(%d)", i)
	}
	return _flateType_name[_flateType_index[i]:_flateType_index[i+1]]
}
